version: "3"
services:
  web:
    container_name: web
    image: webapi
    restart: always
    ports:
      - "8080:80"

  db:
    container_name: db
    image: mysql/mysql-server
    #command: --character-set-server=utf8mb4 --collation-server=utf8mb4_general_ci
    restart: always
    ports:
      - "3306:3306"
    expose:
    # Opens port 3306 on the container
      - '3306'
    volumes:
      - /home/van/Dev/mysql:/var/lib/mysql
    environment:
      - MYSQL_ROOT_PASSWORD=mypassword
      - MYSQL_ROOT_HOST=%
     # - MYSQL_DATABASE=Automatic creation of the DB
     # - MYSQL_USER=User with ALL privilege to ‘MYSQL_DATABASE’
     # - MYSQL_PASSWORD=Password of ‘MYSQL_USER’

  # mongo:
  #     image: mongo
  #     restart: always
  #     ports:
  #       - 27017:27017
  #     environment:
  #       MONGO_INITDB_ROOT_USERNAME: root
  #       MONGO_INITDB_ROOT_PASSWORD: example

  # mongo-express:
  #   image: mongo-express
  #   restart: always
  #   ports:
  #     - 8081:8081
  #   environment:
  #     ME_CONFIG_MONGODB_ADMINUSERNAME: root
  #     ME_CONFIG_MONGODB_ADMINPASSWORD: example